'use client'

import Image from 'next/image'
import Link from 'next/link'
import { Check, Copy, Link2, Plus, Store } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { DashboardHeader } from '@/components/dashboard/dashboard-shell'
import { useDashboardData } from '@/components/dashboard/dashboard-data'
import { generateClientPassword, slugify, type DashboardShop } from '@/data/dashboard'

export default function NewClientPage() {
  const { shops, addShop } = useDashboardData(); const [created, setCreated] = useState<DashboardShop | null>(null); const [form, setForm] = useState({ name: '', location: '', phone: '', category: 'ملابس' })
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }))
  const submit = (event: FormEvent) => { event.preventDefault(); const id = Math.max(0, ...shops.map((item) => item.id)) + 1; const slug = slugify(form.name); const shop: DashboardShop = { id, name: form.name, slug, location: form.location, phone: form.phone, category: form.category, sponsoredAds: 0, joinedAt: new Date().toLocaleDateString('en-CA'), password: generateClientPassword(), logo: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=240&q=85', cover: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=85' }; addShop(shop); setCreated(shop) }
  if (created) { const clientUrl = `${typeof window !== 'undefined' ? window.location.origin : ''}/client-dashboard/${created.slug}`; const qr = `https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(clientUrl)}`; return <><DashboardHeader title="تمت إضافة العميل" description="بيانات دخول العميل جاهزة للمشاركة" /><div className="mx-auto max-w-2xl p-5 py-8 sm:p-8"><section className="rounded-2xl border border-[#cfe7d8] bg-white p-6 text-center sm:p-10"><div className="mx-auto grid size-16 place-items-center rounded-full bg-[#eaf7ef] text-[#087a55]"><Check size={30} /></div><h2 className="mt-5 text-2xl font-bold">تم إنشاء حساب {created.name}</h2><p className="mt-2 text-sm text-[#718078]">احتفظ بالبيانات دي وشاركها مع العميل لبناء لوحة التحكم الخاصة به.</p><div className="mt-7 grid gap-3 text-right sm:grid-cols-2"><div className="rounded-xl bg-[#f6f9f7] p-4"><span className="text-xs text-[#8b9992]">اسم المستخدم</span><b className="mt-1 block text-sm">{created.name}</b></div><div className="rounded-xl bg-[#f6f9f7] p-4"><span className="text-xs text-[#8b9992]">كلمة المرور (11 حرفًا)</span><b className="mt-1 block font-mono text-sm tracking-wider">{created.password}</b></div></div><div className="mt-6 flex flex-col items-center gap-5 rounded-2xl border border-[#e3ebe6] p-5 sm:flex-row"><Image src={qr} alt="QR لوحة العميل" width={150} height={150} className="rounded-lg" /><div className="text-right"><p className="text-sm font-bold">رابط لوحة العميل</p><p className="mt-2 break-all text-xs leading-6 text-[#718078]">{clientUrl}</p><button type="button" onClick={() => navigator.clipboard?.writeText(clientUrl)} className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-[#087a55]"><Copy size={14} /> نسخ الرابط</button></div></div><div className="mt-7 flex gap-3"><Link href="/dashboard/clients" className="inline-flex h-11 flex-1 items-center justify-center rounded-xl border border-[#dce7df] text-sm font-bold">العودة للعملاء</Link><Link href={`/dashboard/clients/${created.id}`} className="inline-flex h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-[#087a55] text-sm font-bold text-white"><Link2 size={16} /> عرض العميل</Link></div></section></div></> }
  return <><DashboardHeader title="إضافة عميل جديد" description="أضف بيانات المحل لإنشاء حسابه على المنصة" /><div className="max-w-3xl p-5 sm:p-8"><form onSubmit={submit} className="rounded-2xl border border-[#e3ebe6] bg-white p-6 sm:p-8"><div className="mb-7 flex items-center gap-3 border-b border-[#edf1ee] pb-5"><span className="grid size-11 place-items-center rounded-xl bg-[#edf8f3] text-[#087a55]"><Store size={21} /></span><div><h2 className="font-bold">بيانات المحل</h2><p className="text-xs text-[#8b9992]">كل البيانات يمكن تعديلها لاحقًا</p></div></div><div className="grid gap-5 sm:grid-cols-2"><Field label="اسم المحل" value={form.name} onChange={(value) => update('name', value)} placeholder="مثال: محل الهدى" required /><Field label="الموقع" value={form.location} onChange={(value) => update('location', value)} placeholder="المنصورة، الدقهلية" required /><Field label="رقم التواصل" value={form.phone} onChange={(value) => update('phone', value)} placeholder="01xxxxxxxxx" required /><label className="block"><span className="mb-2 block text-sm font-bold">الفئة</span><select value={form.category} onChange={(e) => update('category', e.target.value)} className="h-12 w-full rounded-xl border border-[#dce7df] bg-white px-3 text-sm outline-none focus:border-[#087a55]"><option>ملابس</option><option>أحذية</option><option>إلكترونيات</option><option>أكل ومشروبات</option><option>منزل وديكور</option><option>ورد وهدايا</option></select></label></div><div className="mt-8 flex gap-3"><Link href="/dashboard/clients" className="inline-flex h-12 flex-1 items-center justify-center rounded-xl border border-[#dce7df] text-sm font-bold">إلغاء</Link><button type="submit" className="inline-flex h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-[#087a55] text-sm font-bold text-white"><Plus size={17} /> إنشاء حساب العميل</button></div></form></div></>
}
function Field({ label, value, onChange, placeholder, required }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; required?: boolean }) { return <label className="block"><span className="mb-2 block text-sm font-bold">{label}</span><input required={required} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="h-12 w-full rounded-xl border border-[#dce7df] px-4 text-sm outline-none focus:border-[#087a55]" /></label> }
