import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Check, MapPin, MessageCircle, Store } from 'lucide-react'
import { notFound } from 'next/navigation'
import { shops } from '@/data/shops'
import { findShopProduct, type ShopProduct } from '@/data/shop-products'

const legacyProducts: Record<string, Omit<ShopProduct, 'id' | 'shopSlug' | 'shopName'>> = {
  'classic-cotton-tshirt': { name: 'تيشيرت قطن كلاسيك', price: 450, category: 'ملابس', slug: 'classic-cotton-tshirt', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85', description: 'تيشيرت قطني مريح للاستخدام اليومي.', available: true },
  'smart-watch': { name: 'ساعة ذكية', price: 1850, category: 'إلكترونيات', slug: 'smart-watch', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=85', description: 'ساعة ذكية بتصميم عملي للاستخدام اليومي.', available: false },
  'wireless-headphones': { name: 'سماعة لاسلكية', price: 650, category: 'إلكترونيات', slug: 'wireless-headphones', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85', description: 'سماعة لاسلكية بصوت واضح وتصميم مريح.', available: true },
  'everyday-womens-bag': { name: 'حقيبة نسائية يومية', price: 850, category: 'ملابس', slug: 'everyday-womens-bag', image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', description: 'حقيبة عملية بتصميم أنيق للاستخدام اليومي.', available: true },
  'classic-sport-shoes': { name: 'حذاء رياضي كلاسيك', price: 1200, category: 'أحذية', slug: 'classic-sport-shoes', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85', description: 'حذاء رياضي مريح للحركة اليومية.', available: true },
  'fresh-roasted-coffee': { name: 'قهوة محمصة', price: 280, category: 'أكل ومشروبات', slug: 'fresh-roasted-coffee', image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&q=85', description: 'قهوة محمصة بعناية بطعم غني.', available: true },
  'chocolate-gift-box': { name: 'بوكس شوكولاتة', price: 550, category: 'حلويات', slug: 'chocolate-gift-box', image: 'https://images.unsplash.com/photo-1548907040-4d42bfcf2e0a?auto=format&fit=crop&w=900&q=85', description: 'بوكس شوكولاتة مناسب للهدايا والمناسبات.', available: true },
  'chocolate-cake': { name: 'كيك شوكولاتة', price: 420, category: 'حلويات', slug: 'chocolate-cake', image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85', description: 'كيك شوكولاتة طازج بطعم غني.', available: true },
  'fresh-flower-bouquet': { name: 'باقة ورد طبيعية', price: 700, category: 'ورد وهدايا', slug: 'fresh-flower-bouquet', image: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=900&q=85', description: 'باقة ورد طبيعية مرتبة بعناية.', available: true },
  'decorative-lamp': { name: 'أباجورة ديكور', price: 980, category: 'منزل وديكور', slug: 'decorative-lamp', image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=85', description: 'أباجورة تضيف لمسة دافئة للبيت.', available: true },
  'oriental-perfume': { name: 'عطر شرقي', price: 620, category: 'تجميل وعناية', slug: 'oriental-perfume', image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=85', description: 'عطر شرقي برائحة ثابتة ومميزة.', available: true },
  'butter-croissant': { name: 'كرواسون بالزبدة', price: 95, category: 'أكل ومشروبات', slug: 'butter-croissant', image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=85', description: 'كرواسون طازج ومخبوز يوميًا.', available: true },
}

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const generated = findShopProduct(slug, shops)
  const legacy = legacyProducts[slug]
  const product = generated ?? (legacy ? { ...legacy, id: 0, shopSlug: 'ahmed-fashion', shopName: 'أحمد فاشون' } : undefined)
  if (!product) notFound()
  const whatsappMessage = encodeURIComponent(`مرحبًا، أريد الاستفسار عن منتج "${product.name}" بسعر ${product.price} جنيه.`)
  const location = shops.find((shop) => shop.slug === product.shopSlug)?.location ?? 'المنصورة'
  return <main dir="rtl" className="min-h-screen bg-[#fbfcfa] py-8 text-[#17231d] md:py-14"><section className="mx-auto grid max-w-[1100px] gap-8 px-5 sm:px-8 lg:grid-cols-2 lg:items-center"><div className="overflow-hidden rounded-3xl border border-[#e1ebe5] bg-white shadow-[0_8px_35px_rgba(23,35,29,0.06)]"><Image src={product.image} alt={product.name} width={900} height={900} className="aspect-square w-full object-cover" /></div><div><span className="inline-flex rounded-full bg-[#edf8f3] px-3 py-1.5 text-xs font-semibold text-[#087a55]">{product.category}</span><h1 className="mt-5 text-3xl font-bold tracking-tight sm:text-4xl">{product.name}</h1><p className="mt-5 text-2xl font-bold text-[#087a55]">{product.price} جنيه</p><div className="mt-8 space-y-4 border-y border-[#e1ebe5] py-6"><Link href={`/store/${product.shopSlug}`} className="flex items-center gap-3 transition hover:text-[#087a55]"><span className="flex size-10 items-center justify-center rounded-xl bg-[#edf8f3] text-[#087a55]"><Store size={18} /></span><span><span className="block text-xs text-[#718078]">المحل</span><span className="text-sm font-bold">{product.shopName}</span></span></Link><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-[#edf8f3] text-[#087a55]"><MapPin size={18} /></span><span><span className="block text-xs text-[#718078]">المكان</span><span className="text-sm font-semibold">{location}</span></span></div><div className={`flex items-center gap-3 text-sm font-semibold ${product.available ? 'text-[#087a55]' : 'text-[#9a6258]'}`}><Check size={18} />{product.available ? 'المنتج متوفر حاليًا' : 'المنتج غير متوفر حاليًا'}</div></div><div className="mt-7 flex flex-col gap-3 sm:flex-row">{product.available && <a href={`https://wa.me/201023522063?text=${whatsappMessage}`} target="_blank" rel="noopener noreferrer" className="inline-flex h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-[#087a55] px-5 text-sm font-bold text-white transition hover:bg-[#066847]"><MessageCircle size={18} /> تواصل مع صاحب المحل للشراء</a>}<Link href={`/store/${product.shopSlug}`} className="inline-flex h-12 flex-1 items-center justify-center gap-2 rounded-xl border border-[#dce7e1] bg-white px-5 text-sm font-bold text-[#087a55] transition hover:bg-[#f3f8f5]">عرض المزيد من المنتجات <ArrowRight size={16} /></Link></div></div></section></main>
}
