'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useMemo, useState } from 'react'
import { ArrowLeft, Check, Clock3, ExternalLink, Heart, MapPin, MessageCircle, Phone, Search, Share2, ShieldCheck, ShoppingBag, Star, X } from 'lucide-react'
import { makeShopProducts, type ShopProduct } from '@/data/shop-products'
import { shops, type Shop } from '@/data/shops'

export default function StorePageClient({ shop }: { shop: Shop }) {
  const [query, setQuery] = useState('')
  const [liked, setLiked] = useState<number[]>([])
  const [quickProduct, setQuickProduct] = useState<ShopProduct | null>(null)
  const [activeCategory, setActiveCategory] = useState('الكل')
  const products = useMemo(() => makeShopProducts(shop.name, shop.category, shop.slug), [shop])
  const categories = ['الكل', ...Array.from(new Set(products.map((product) => product.category)))]
  const filteredProducts = products.filter((product) => (activeCategory === 'الكل' || product.category === activeCategory) && product.name.includes(query))
  const relatedShops = useMemo(() => shops.filter((item) => item.slug !== shop.slug && (item.categorySlug === shop.categorySlug || item.governorate === shop.governorate)).slice(0, 3), [shop])
  const whatsapp = shop.whatsapp ?? '201023522063'
  const phone = shop.phone ?? '01023522063'
  const mapsUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${shop.address ?? shop.location}، ${shop.governorate}`)}`
  const toggleLike = (id: number) => setLiked((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])

  return <main dir="rtl" className="min-h-screen bg-[#fbfcfa] text-[#17231d]">
    <section className="mx-auto max-w-[1240px] px-4 pt-4 sm:px-8 sm:pt-7">
      <div className="relative h-[230px] overflow-hidden rounded-[28px] bg-[#dce8e1] sm:h-[330px] lg:h-[390px]"><Image src={shop.cover} alt={`غلاف ${shop.name}`} fill sizes="(max-width: 1024px) 100vw, 1240px" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#17231d]/75 via-[#17231d]/15 to-transparent" /><div className="absolute bottom-6 right-5 text-white sm:bottom-9 sm:right-9"><p className="mb-2 text-xs font-semibold text-white/80">متجر محلي موثّق</p><h1 className="text-2xl font-bold sm:text-4xl">{shop.name}</h1></div></div>
      <div className="relative -mt-8 rounded-[24px] border border-[#e2ebe5] bg-white px-5 pb-5 pt-0 shadow-[0_8px_30px_rgba(23,35,29,0.06)] sm:-mt-11 sm:px-8 sm:pb-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-end"><div className="relative -mt-10 h-20 w-20 shrink-0 overflow-hidden rounded-2xl border-4 border-white bg-[#eaf3ee] shadow-md sm:h-24 sm:w-24"><Image src={shop.logo} alt={`شعار ${shop.name}`} fill sizes="96px" className="object-cover" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold sm:text-2xl">{shop.name}</h2><span className="inline-flex items-center gap-1 text-xs font-bold text-[#087a55]"><ShieldCheck size={15} /> موثوق</span></div><p className="mt-1 text-sm leading-6 text-[#66756d]">{shop.description}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-[#718078]"><span className="inline-flex items-center gap-1.5"><ShoppingBag size={14} className="text-[#087a55]" />{shop.category}</span><span className="inline-flex items-center gap-1.5"><MapPin size={14} className="text-[#087a55]" />{shop.location}، {shop.governorate}</span><span className="inline-flex items-center gap-1.5 font-semibold text-[#087a55]"><span className="h-2 w-2 rounded-full bg-[#2ba875]" />مفتوح الآن</span></div></div><div className="flex shrink-0 gap-2"><a href={`https://wa.me/${whatsapp}?text=${encodeURIComponent(`مرحبًا، أريد الاستفسار عن منتجات محل ${shop.name}`)}`} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#087a55] px-4 text-xs font-bold text-white"><MessageCircle size={16} /> واتساب</a><a href={`tel:${phone}`} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#dce7df] px-4 text-xs font-bold text-[#087a55]"><Phone size={16} /> اتصال</a><button type="button" onClick={() => navigator.share?.({ title: shop.name, url: window.location.href })} className="hidden h-10 w-10 items-center justify-center rounded-xl border border-[#dce7df] text-[#68786f] sm:flex" aria-label="مشاركة المتجر"><Share2 size={16} /></button></div></div></div>
    </section>
    <nav className="mt-5 border-y border-[#e5eee8] bg-white"><div className="mx-auto flex max-w-[1240px] gap-7 overflow-x-auto px-5 text-sm font-bold text-[#718078] [scrollbar-width:none] sm:px-8"><a href="#products" className="border-b-2 border-[#087a55] py-4 text-[#087a55]">المنتجات</a><a href="#about" className="whitespace-nowrap py-4 hover:text-[#087a55]">عن المحل</a><a href="#location" className="whitespace-nowrap py-4 hover:text-[#087a55]">الموقع والتواصل</a></div></nav>
    <div className="mx-auto max-w-[1240px] px-5 py-8 sm:px-8 sm:py-12"><div className="grid grid-cols-2 gap-3 rounded-[22px] border border-[#e0ebe4] bg-[#f7f5ef] p-4 sm:grid-cols-4 sm:p-5"><Info icon={<MapPin size={17} />} label="الموقع" value={shop.location} /><Info icon={<ShoppingBag size={17} />} label="المنتجات" value={`${shop.productsCount} منتج`} /><Info icon={<Clock3 size={17} />} label="مواعيد العمل" value={shop.workingHours ?? 'يوميًا 10 ص - 10 م'} /><Info icon={<Check size={17} />} label="الخدمة" value={shop.deliveryAvailable === false ? 'استلام من المحل' : 'توصيل متاح'} /></div>
      <section id="products" className="mt-12"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-wide text-[#087a55]">تصفح المجموعة</p><h2 className="mt-1 text-2xl font-bold">منتجات المحل <span className="text-base font-medium text-[#8a9891]">({filteredProducts.length})</span></h2></div><div className="relative w-full sm:w-72"><Search className="absolute right-4 top-1/2 -translate-y-1/2 text-[#84948b]" size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ابحث في منتجات المحل..." className="h-12 w-full rounded-xl border border-[#dce7df] bg-white pr-11 pl-4 text-sm outline-none focus:border-[#087a55]" /></div></div><div className="mt-6 flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none]">{categories.map((category) => <button type="button" key={category} onClick={() => setActiveCategory(category)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-bold ${activeCategory === category ? 'bg-[#087a55] text-white' : 'border border-[#e0eae3] bg-white text-[#718078]'}`}>{category}</button>)}</div><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 lg:gap-5">{filteredProducts.map((product) => <ProductCard key={product.id} product={product} liked={liked.includes(product.id)} onLike={() => toggleLike(product.id)} onQuick={() => setQuickProduct(product)} />)}</div></section>
      <section id="about" className="mt-14 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[24px] border border-[#e1ebe5] bg-white p-6 sm:p-8"><p className="text-xs font-bold text-[#087a55]">عن المحل</p><h2 className="mt-2 text-2xl font-bold">أهلاً بيك في {shop.name}</h2><p className="mt-4 text-sm leading-7 text-[#718078]">{shop.longDescription ?? shop.description} نحرص على تقديم تجربة بسيطة وواضحة، مع منتجات مختارة بعناية وتواصل مباشر يساعدك تختار الأنسب ليك.</p><div className="mt-7 grid gap-4 text-sm text-[#5f7067] sm:grid-cols-2"><Info icon={<MapPin size={18} />} label="العنوان" value={shop.address ?? shop.location} /><Info icon={<Star size={18} />} label="تقييم المحل" value="4.9 من 5" /><Info icon={<Check size={18} />} label="طرق الدفع" value={shop.paymentMethods?.join('، ') ?? 'نقدي، تحويل بنكي'} /><Info icon={<ShoppingBag size={18} />} label="التوصيل" value={shop.deliveryAvailable === false ? 'غير متاح' : 'داخل المنطقة'} /></div></div><div id="location" className="flex min-h-[280px] flex-col justify-between rounded-[24px] bg-[#dce9e0] p-6 sm:p-8"><div><p className="text-xs font-bold text-[#087a55]">زورنا</p><h2 className="mt-2 text-2xl font-bold">المحل قريب منك</h2><p className="mt-3 text-sm leading-6 text-[#607068]">{shop.address ?? shop.location}، {shop.governorate}</p></div><div className="flex h-28 items-center justify-center rounded-2xl border border-white/70 bg-white/35 text-sm font-bold text-[#718078]"><MapPin size={18} className="ml-2 text-[#087a55]" /> موقع المحل على الخريطة</div><a href={mapsUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-white text-sm font-bold text-[#087a55]"><ExternalLink size={16} /> فتح على خرائط Google</a></div></section>
      <section className="mt-14 rounded-[26px] bg-[#087a55] p-7 text-white sm:p-10"><div className="flex flex-col justify-between gap-7 sm:flex-row sm:items-center"><div><p className="text-sm font-bold text-white/70">محتاج تعرف أكتر؟</p><h2 className="mt-2 text-2xl font-bold">تواصل مع {shop.name}</h2><p className="mt-2 text-sm text-white/75">اسأل عن منتج، اطلب عرض سعر، أو اعرف مواعيد العمل.</p></div><div className="flex flex-wrap gap-3"><a href={`https://wa.me/${whatsapp}`} className="inline-flex h-11 items-center gap-2 rounded-xl bg-white px-5 text-sm font-bold text-[#087a55]"><MessageCircle size={17} /> واتساب</a><a href={`tel:${phone}`} className="inline-flex h-11 items-center gap-2 rounded-xl border border-white/30 px-5 text-sm font-bold text-white"><Phone size={17} /> اتصل بالمحل</a></div></div></section>
      {relatedShops.length > 0 && <section className="mt-14"><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-bold text-[#087a55]">اكتشف أكتر</p><h2 className="mt-1 text-2xl font-bold">محلات ممكن تعجبك</h2></div><Link href="/stores" className="text-sm font-bold text-[#087a55]">كل المحلات <ArrowLeft size={14} className="mr-1 inline" /></Link></div><div className="grid gap-4 sm:grid-cols-3">{relatedShops.map((item) => <Link key={item.id} href={`/store/${item.slug}`} className="group overflow-hidden rounded-2xl border border-[#e1ebe5] bg-white"><Image src={item.cover} alt={item.name} width={900} height={320} className="h-32 w-full object-cover transition group-hover:scale-105" /><div className="p-4"><h3 className="font-bold">{item.name}</h3><p className="mt-1 text-sm text-[#718078]">{item.category} · {item.location}</p></div></Link>)}</div></section>}
    </div>
    <footer className="border-t border-[#e3ece6] bg-white"><div className="mx-auto flex max-w-[1240px] flex-col gap-3 px-5 py-8 text-sm text-[#718078] sm:flex-row sm:items-center sm:justify-between sm:px-8"><span className="font-bold text-[#17231d]">محلي</span><span>منصة المحلات المحلية المفضلة عندك</span><Link href="/stores" className="font-semibold text-[#087a55]">اكتشف محلات تانية <ArrowLeft size={14} className="mr-1 inline" /></Link></div></footer>
    {quickProduct && <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#17231d]/45 p-0 sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-label="تفاصيل المنتج"><div className="relative max-h-[90vh] w-full overflow-y-auto rounded-t-[28px] bg-white p-5 sm:max-w-[680px] sm:rounded-[28px] sm:p-7"><button type="button" onClick={() => setQuickProduct(null)} className="absolute left-4 top-4 rounded-full bg-[#f2f6f3] p-2 text-[#627269]" aria-label="إغلاق"><X size={18} /></button><div className="grid gap-6 sm:grid-cols-2"><Image src={quickProduct.image} alt={quickProduct.name} width={800} height={800} className="aspect-square w-full rounded-2xl object-cover" /><div className="flex flex-col justify-center"><p className="text-xs font-bold text-[#087a55]">{quickProduct.category}</p><h2 className="mt-2 text-2xl font-bold">{quickProduct.name}</h2><p className="mt-4 text-sm leading-7 text-[#718078]">{quickProduct.description}</p><p className="mt-5 text-2xl font-bold text-[#087a55]">{quickProduct.price} جنيه</p><p className={`mt-4 text-sm font-bold ${quickProduct.available ? 'text-[#087a55]' : 'text-[#9a6258]'}`}>{quickProduct.available ? 'متوفر حاليًا' : 'غير متوفر حاليًا'}</p><a href={`https://wa.me/${whatsapp}?text=${encodeURIComponent(`مرحبًا، أريد الاستفسار عن ${quickProduct.name}`)}`} className="mt-7 inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[#087a55] text-sm font-bold text-white"><MessageCircle size={17} /> اطلب عبر واتساب</a></div></div></div></div>}
  </main>
}

function Info({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <span className="flex items-start gap-3 text-sm text-[#5f7067]"><span className="mt-0.5 shrink-0 text-[#087a55]">{icon}</span><span><b className="block text-xs font-bold text-[#17231d]">{label}</b>{value}</span></span> }
function ProductCard({ product, liked, onLike, onQuick }: { product: ShopProduct; liked: boolean; onLike: () => void; onQuick: () => void }) { return <article className="group relative overflow-hidden rounded-2xl border border-[#e1ebe5] bg-white transition hover:-translate-y-0.5 hover:shadow-[0_10px_25px_rgba(23,35,29,0.08)]"><Link href={`/product/${product.slug}`} className="block"><div className="relative aspect-[.92] overflow-hidden bg-[#edf3ef]"><Image src={product.image} alt={product.name} fill sizes="(max-width: 640px) 50vw, (max-width: 1024px) 33vw, 25vw" className="object-cover transition duration-500 group-hover:scale-105" /><span className={`absolute bottom-2 left-2 rounded-lg px-2 py-1 text-[10px] font-bold ${product.available ? 'bg-white/90 text-[#087a55]' : 'bg-[#17231d]/75 text-white'}`}>{product.available ? 'متوفر' : 'نفد'}</span></div><div className="p-3 sm:p-4"><h3 className="truncate text-sm font-bold text-[#24342b] sm:text-base">{product.name}</h3><span className="mt-2 block text-sm font-bold text-[#087a55] sm:text-base">{product.price} جنيه</span></div></Link><div className="absolute left-2 top-2 flex gap-1.5"><button type="button" onClick={onLike} className="flex h-8 w-8 items-center justify-center rounded-full bg-white/90 text-[#65766d] shadow-sm" aria-label={liked ? 'إزالة من المفضلة' : 'إضافة للمفضلة'}><Heart size={15} fill={liked ? '#e36f69' : 'none'} className={liked ? 'text-[#e36f69]' : ''} /></button><button type="button" onClick={onQuick} className="hidden h-8 w-8 items-center justify-center rounded-full bg-white/90 text-[#65766d] shadow-sm sm:flex" aria-label={`عرض سريع ${product.name}`}><ExternalLink size={14} /></button></div></article> }
