'use client'

import Link from 'next/link'
import { ArrowRight, ImagePlus, Megaphone, Save } from 'lucide-react'
import { FormEvent, useEffect, useState } from 'react'
import { useParams, useRouter, useSearchParams } from 'next/navigation'
import { DashboardHeader } from '@/components/dashboard/dashboard-shell'
import { useDashboardData } from '@/components/dashboard/dashboard-data'
import { type SponsoredAd } from '@/data/dashboard'

export default function SponsoredAdPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const search = useSearchParams(); const adId = Number(search.get('ad')); const { shops, ads, addAd, updateAd } = useDashboardData(); const shop = shops.find((item) => item.id === Number(id)); const existing = ads.find((ad) => ad.id === adId && ad.shopId === Number(id)); const [form, setForm] = useState({ title: '', description: '', phone: '', image: '', status: 'نشط' as SponsoredAd['status'] })
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (existing) setForm({ title: existing.title, description: existing.description, phone: existing.phone, image: existing.image, status: existing.status }); else if (shop) setForm((current) => ({ ...current, phone: shop.phone, image: shop.cover })) }, [existing, shop])
  if (!shop) return <div className="p-8">العميل غير موجود.</div>
  const submit = (event: FormEvent) => { event.preventDefault(); if (existing) updateAd({ ...existing, ...form }); else addAd({ id: Math.max(0, ...ads.map((item) => item.id)) + 1, shopId: shop.id, ...form }); router.push(`/dashboard/clients/${shop.id}`) }
  return <><DashboardHeader title={existing ? 'تعديل إعلان ممول' : 'إضافة إعلان ممول'} description={`إدارة إعلان ${shop.name}`} /><div className="max-w-3xl p-5 sm:p-8"><form onSubmit={submit} className="rounded-2xl border border-[#e3ebe6] bg-white p-6 sm:p-8"><div className="mb-7 flex items-center gap-3 border-b border-[#edf1ee] pb-5"><span className="grid size-11 place-items-center rounded-xl bg-[#fff4df] text-[#bd7c12]"><Megaphone size={21} /></span><div><h2 className="font-bold">بيانات الإعلان</h2><p className="text-xs text-[#8b9992]">أضف صورة ومحتوى الإعلان ورقم التواصل</p></div></div><div className="space-y-5"><Field label="عنوان الإعلان" value={form.title} onChange={(v) => setForm({ ...form, title: v })} placeholder="مثال: خصم خاص لفترة محدودة" /><label className="block"><span className="mb-2 block text-sm font-bold">وصف الإعلان</span><textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows={4} placeholder="اكتب وصفًا مختصرًا وجذابًا للإعلان..." className="w-full resize-none rounded-xl border border-[#dce7df] p-4 text-sm outline-none focus:border-[#087a55]" /></label><Field label="رابط / صورة الإعلان" value={form.image} onChange={(v) => setForm({ ...form, image: v })} placeholder="https://images.unsplash.com/..." /><div className="grid gap-5 sm:grid-cols-2"><Field label="رقم التواصل للإعلان" value={form.phone} onChange={(v) => setForm({ ...form, phone: v })} placeholder="01xxxxxxxxx" /><label className="block"><span className="mb-2 block text-sm font-bold">حالة الإعلان</span><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as SponsoredAd['status'] })} className="h-12 w-full rounded-xl border border-[#dce7df] bg-white px-3 text-sm outline-none focus:border-[#087a55]"><option>نشط</option><option>مسودة</option></select></label></div><div className="flex items-center gap-3 rounded-xl bg-[#f6f9f7] p-4 text-xs leading-6 text-[#718078]"><ImagePlus size={19} className="shrink-0 text-[#087a55]" />الصورة تُحفظ كرابط مؤقت حاليًا، ويمكن ربطها برفع ملفات حقيقي عند بناء الـ Backend.</div></div><div className="mt-8 flex gap-3"><Link href={`/dashboard/clients/${shop.id}`} className="inline-flex h-12 flex-1 items-center justify-center gap-2 rounded-xl border border-[#dce7df] text-sm font-bold"><ArrowRight size={16} /> إلغاء</Link><button type="submit" className="inline-flex h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-[#087a55] text-sm font-bold text-white"><Save size={17} /> {existing ? 'حفظ الإعلان' : 'إضافة الإعلان'}</button></div></form></div></>
}
function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="block"><span className="mb-2 block text-sm font-bold">{label}</span><input required value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="h-12 w-full rounded-xl border border-[#dce7df] px-4 text-sm outline-none focus:border-[#087a55]" /></label> }
